version: "3"
services:
  server:
    image: local.repo/meetingroomdisplay:latest
    environment:
      - EWS_ENDPOINT=https://exchange.domain.xxx/ews/Exchange.asmx
      - EWS_USER=svc-exchange-user
      - EWS_PASS=
      - EWS_DOMAIN=@domain.de
      - DEFAULTROOM=Conference1
    restart: always
    deploy:
      replicas: 1
      labels:
        - "traefik.port=9393"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:mrd.docker.local"
        - "traefik.enable=true"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true